services:
  web:
    image: php:8.2-apache
    container_name: php-apachelume
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=lume_db
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile


  db:
    image: mysql:8.0
    container_name: mysql-dblume
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lume_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminlume
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network


volumes:
  db_data:


networks:
  app-network:
